version: '3.7'

services:
  server:
    command: "python3 manage.py runserver 0.0.0.0:8000 --noreload"
    ports:
      - "8000:8000"
    env_file:
      - vars.env
    image: huliinc_django
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app