version: '3.7'

services:
  server:
    command: "python3 manage.py runserver"
    ports:
      - "8000:8000"
    image: huliinc_django
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    networks:
      - huliinc_net

networks:
  huliinc_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
      com.docker.network.bridge.name: "r_docker_net"